$schema: 'https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json'
console_title_template: '{{.Folder}}{{if .Root}} :: root{{end}} :: {{.Shell}}'
final_space: true
version: 3
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: time
        style: plain
        foreground: '#ffffff'
        properties:
          time_format: '⏩ <b>15:04:05<b>'
      - type: command
        style: plain
        foreground: '#ffffff'
        template: '<b>{{ .Output }}</b>'
        properties:
          shell: bash
          script: $(DOTFILES_PATH)/scripts/get_hostname_emoji.sh
      - type: status
        style: plain
        foreground: '#ffffff'
        template: '{{ if eq .Code 0 }}{{ else }} 🔴{{ end }}'
        properties:
          always_enabled: true
      - type: path
        style: plain
        foreground: '#ffffff'
        properties:
          style: agnoster_short
          max_depth: 3
      - type: git
        style: plain
        foreground: '#ffffff'
        properties:
          display_status: true
          display_stash_count: true
          display_upstream_icon: false
          fetch_status: true
          fetch_upstream_icon: false
        template: '<u>{{.RepoName}}/{{.Ref}}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }}{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}</u>'
  - type: rprompt
    alignment: left
    segments:
      - type: kubectl
        style: plain
        foreground: '#ffffff'
        properties:
          template: '{{ .Context }}:{{ .Namespace }}'
      - type: terraform
        style: plain
        foreground: '#ffffff'
        properties:
          template: '{{ .Workspace }}'
transient_prompt:
  background: transparent
  foreground: p:white
  template: ' '
