# Atuin configuration file

## possible values: global, host, session, directory
filter_mode = "host"

show_help = true
secrets_filter = true
enter_accept = true

[stats]
## Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
    "docker",
    "git",
    "go",
    "kubectl",
    "systemctl",
    "tmux",
    "yarn",
    "npm",
]
ignored_commands = ["cd", "ls", "la", "a", "gst"]

[sync]
records = true

# https://docs.atuin.sh/guide/dotfiles/
[dotfiles]
enabled = true
